version: "3.9"
services:
  rp:
    container_name: "rp"
    image: "nginx:latest"
    ports:
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
  web:
    container_name: "web"
    image: "nginx"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html